### ISSUE TITLE
Chapter2.3 のBigQueryへの書き込みサンプルについて

### ISSUE THREAD

**Issue by rai-suta** [hayatoy/gcpml-book#1]
[Part1/Chapter2.3.ipynb](https://github.com/hayatoy/gcpml-book/blob/master/Part1/Chapter2.3.ipynb)にてpandas DataFrameからBigQueryに書き込むサンプルを実行すると、Tracebackが走ってしまい、最終的に下記エラーで止まってしまいました。

```
/usr/local/lib/python2.7/dist-packages/google/cloud/_http.pyc in api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object)
    291 
    292         if not 200 <= response.status_code < 300:
--> 293             raise exceptions.from_http_response(response)
    294 
    295         if expect_json and response.content:

NotFound: 404 GET https://www.googleapis.com/bigquery/v2/projects/test-project-194108/datasets/testdataset/tables/names2: Not found: Table test-project-194108:testdataset.names2
```
しばらく悩んでいたのですが、Select kernel にてPython3を選択すると、問題なく実行できるようでしたのでご報告まで。

**Comment by hayatoy** [comment]
@rai-suta さん
ありがとうございます。こちらでも再現しました。
どうも現在のDatalabにインストール済みのパッケージバージョン不整合のように見えます。
`!pip install google-cloud-bigquery` でPython2でも正常に書き込む事ができました。

なお、`to_gbq`は書き込み先テーブルが存在する場合、デフォルトではfailになります。
上記`pip instll`をして`to_gbq`をやり直す場合は、作成済みのテーブルを削除するか、`if_exists="append"`などの引数を追加してください。
